Updated App, added landing page and added react-router-dom
Joy-of-Coding/Winter_2023_ReactJam pull request #3
Opened 2023-12-28 21:15 UTC by TishShaw

### **Overview**
This pull request introduces the opening screen for the app and integrates React Router DOM for efficient page routing.

### **Changes Made:**

- **Integration of React Router DOM**: Added React Router DOM to enable dynamic page routing throughout the application.

- **Modification to main.jsx**: Implemented BrowserRouter as Router in main.jsx to ensure React Router DOM functionality is accessible app-wide.

- **Update to App.jsx**: Defined the various paths used in the application to facilitate navigation. Enhanced the structure to support the addition of new routes.

- **Creation of Home.jsx**: Developed the opening screen interface.
Included essential elements such as:

     - A prominent title display.
      
     - A 'Start' button, which on activation, navigates the user to the game area.
      
     - A static 'How to' button, intended to provide guidance and instructions for new users

2023-12-28 21:30 UTC, LMMSWDesigner approved these changes

2023-12-28 23:14 UTC, KatrinaWright requested changes
I tested the branch, and it seemed to have lost the styling for the gameboard - please re add this import back into the App.jsx and then it can be merged into main

import './App.css'

2023-12-28 23:14 UTC, LMMSWDesigner commented
Return the statement 

import './App.css'

to App.jsx

2023-12-28 23:47 UTC, LMMSWDesigner approved these changes
Fixed css issue

2023-12-29 01:16 UTC, AdventureBear requested changes
here is no need to add react router to this project. Doing so is missing a key feature of reacts ability to conditionally show and hide components. We want conditional rendering for the start screen, not a new route.

2023-12-29 01:16 UTC, AdventureBear commented on reverse-pacman/package.json
there is no need to add react router to this project.  Doing so is missing a key feature of reacts ability to conditionally show and hide components.  We want conditional rendering for the start screen, not a new route.

2023-12-29 04:18 UTC, TishShaw commented
I've removed the dependency on react-router-dom, incorporated App.css directly into App.jsx, and used useState hook to elevate state from home.jsx to app.jsx.

2023-12-29 04:30 UTC, AdventureBear requested changes
Everything looks good except main.jsx still has the browser router references. Once those are removed it will be good to merge! Godod job.

2023-12-29 04:30 UTC, AdventureBear commented on reverse-pacman/src/main.jsx
this is the only file that still needs to be reverted by removing the Router references.  Everything else looks and works great.

2023-12-29 15:45 UTC, KatrinaWright approved these changes
Tested - looks great! 
Thank you for resolving those changes with the app.css and the routing! It looks so cool now!
Merging into main <3

2023-12-29 15:46 UTC, KatrinaWright approved these changes
This is a test to see if I can resolve this request through the GUI as well

2023-12-29 16:26 UTC, AdventureBear approved these changes

2023-12-29 16:26 UTC, merged

2023-12-29 16:52 UTC, LMMSWDesigner reviewed
This is fine. It works.